"""Cria tabelas iniciais

Revision ID: 256ac05f002f
Revises: 
Create Date: 2026-04-24 20:13:15.827389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256ac05f002f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('nacionalidade', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_morte', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('fonte', sa.String(length=255), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edicoes_premio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['premio_id'], ['premios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('editora', sa.String(length=255), nullable=True),
    sa.Column('idioma_original', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('capa_url', sa.String(length=500), nullable=True),
    sa.Column('link_afiliado', sa.String(length=500), nullable=True),
    sa.Column('short_url', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autores_premio',
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('colocacao', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes_premio.id'], ),
    sa.PrimaryKeyConstraint('autor_id', 'edicao_id')
    )
    op.create_table('categorias_premio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes_premio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros_lista',
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('redator', sa.String(length=255), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('livro_id', 'lista_id', 'redator')
    )
    op.create_table('livros_categoria',
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('colocacao', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_premio.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('livro_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros_categoria')
    op.drop_table('livros_lista')
    op.drop_table('categorias_premio')
    op.drop_table('autores_premio')
    op.drop_table('livros')
    op.drop_table('edicoes_premio')
    op.drop_table('premios')
    op.drop_table('listas')
    op.drop_table('autores')
    # ### end Alembic commands ###
