"""Adiciona campos destaque e ordem_destaque em Premio e Lista

Revision ID: 37c2b4813a6f
Revises: a37ef1c0e579
Create Date: 2026-05-08 20:57:38.630762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c2b4813a6f'
down_revision: Union[str, Sequence[str], None] = 'a37ef1c0e579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listas', sa.Column('destaque', sa.Integer(), nullable=True))
    op.add_column('listas', sa.Column('ordem_destaque', sa.Integer(), nullable=True))
    op.add_column('premios', sa.Column('destaque', sa.Integer(), nullable=True))
    op.add_column('premios', sa.Column('ordem_destaque', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premios', 'ordem_destaque')
    op.drop_column('premios', 'destaque')
    op.drop_column('listas', 'ordem_destaque')
    op.drop_column('listas', 'destaque')
    # ### end Alembic commands ###
