"""Adiciona campo tradutor em livros

Revision ID: a37ef1c0e579
Revises: 256ac05f002f
Create Date: 2026-04-30 22:28:12.039717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37ef1c0e579'
down_revision: Union[str, Sequence[str], None] = '256ac05f002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('tradutor', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'tradutor')
    # ### end Alembic commands ###
